# Access http://oauth2-proxy.localtest.me:4180 to initiate a login cycle using user=admin@example.com, password=password
# Access http://keycloak.localtest.me:9080 with the same credentials to check out the settings
services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    ports:
      - 4180:4180/tcp
    networks:
      keycloak: {}
      frontend: {}
      oauth2-proxy: {}
    depends_on:
      - frontend
      - keycloak

  frontend:
    image: joseluisq/static-web-server:2-alpine
    container_name: "frontend"
    ports:
      - 8088:80
    restart: unless-stopped
    environment:
      - SERVER_ROOT=/var/public
    volumes:
      - ./frontend/dist:/var/public
    networks:
      frontend:
        aliases:
          - frontend.localtest.me

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0
    hostname: keycloak
    command:
      - 'start-dev'
      - '--http-port=9080'
      - '--import-realm'
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KC_HTTP_PORT: 9080
      KEYCLOAK_ADMIN: admin@example.com
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 9080:9080/tcp
    networks:
      keycloak:
        aliases:
          - keycloak.localtest.me

networks:
  frontend: {}
  keycloak: {}
  oauth2-proxy: {}
